### ISSUE TITLE
Windows tests broken

### ISSUE THREAD

**Issue by danielparks** [danielparks/puppetlabs-distelli_agent#9]
From https://github.com/puppetlabs/puppetlabs-distelli_agent/pull/4#issuecomment-371717976:

`file:///c:…` fixed the absolute path problem, but now I have a new error:

~~~
  1) pipelines::agent on windows-2008 R2-x64 should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile }
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/provider/user/windows_adsi.rb:17:in `initialize'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/provider/user/windows_adsi.rb:17:in `new'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/provider/user/windows_adsi.rb:17:in `user'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/provider/user/windows_adsi.rb:21:in `groups'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type/user.rb:332:in `retrieve'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/property/list.rb:37:in `should'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type/user.rb:449:in `block (2 levels) in <module:Puppet>'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2142:in `instance_eval'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2142:in `block in autorelation'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2081:in `block in eachautorequire'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2080:in `each'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2080:in `eachautorequire'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2137:in `autorelation'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/type.rb:2169:in `autorequire'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:172:in `block (2 levels) in build_autorelation_dependencies'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:171:in `each'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:171:in `block in build_autorelation_dependencies'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:170:in `each'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:170:in `build_autorelation_dependencies'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/graph/relationship_graph.rb:25:in `populate_from'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-5.4.0/lib/puppet/resource/catalog.rb:262:in `relationship_graph'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-puppet-2.6.11/lib/rspec-puppet/matchers/compile.rb:142:in `cycles_found?'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-puppet-2.6.11/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/classes/agent_spec.rb:12:in `block (4 levels) in <top (required)>'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'
~~~

Weird.

**Comment by brimworks** [comment]
Fixed in this PR: https://github.com/puppetlabs/puppetlabs-distelli_agent/pull/6
